---
# tasks file for download-war
- name: delete everything in /var/lib/tomcat8/webapps
  become: true
  file:
    path: /var/lib/tomcat8/webapps/
    state: absent

- name: make dir /var/lib/tomcat8/webapps
  become: true
  file:
    path: /var/lib/tomcat8/webapps
    state: directory
    mode: 755

- name: Download war file
  become: true
  get_url:
    url: https://tomcat.apache.org/tomcat-8.0-doc/appdev/sample/sample.war
    dest: /var/lib/tomcat8/webapps/ROOT.war
    owner: tomcat8
    mode: 755
    



    
 
