---
# tasks file for nginx-reverse-proxy
- hosts: all
  roles:
     - install-nginx
     - install-tomcat
     - nginx-reverse-proxy 
     

  become: true
  file:
    path: /var/lib/tomcat8/webapps/*
    state: absent

